### ISSUE TITLE
Setup react-testing-library

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/react-structural-metadata-editor#8]
### Description
Setup the testing infrastructure for `react-testing-library`, which will replace our previous reliance upon `enzyme`.  

https://github.com/testing-library/react-testing-library
https://testing-library.com/react

https://github.com/airbnb/enzyme

### Done Looks Like
- All packages are in place and tested to support the React Testing Library in our project

### Tasks
- [x] Install all necessary packages
- [x] Test within our application the setup works seamlessly
- [x] Write basic sample test
